name: AmrCompany
services:
  admin_webserver:
    container_name: admin_panel
    build: ./php-fpm/
    volumes:
      - ../website/admin/:/var/www/html/

  app_webserver:
    container_name: web_app
    build: ./php-fpm/
    volumes:
      - ../website/app/:/var/www/html/

  landing_webserver:
    container_name: landing_page
    build: ./php-fpm/
    volumes:
      - ../website/main/:/var/www/html/

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - admin_webserver
      - app_webserver
      - landing_webserver
    


  # database:
  #   image: postgres:14.21-alpine3.23